server:
  port: 8001
spring:
  application:
    name: provider
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8847
      config:
        server-addr: localhost:8847
        file-extension: yaml #指定yaml格式的配置
  sleuth:
    sampler:
      probability: 1 # 采样率0-1
  zipkin:
    base-url: http://localhost:9411
#        group: DEV_GROUP
#        namespace: 7d8f0f5a-6a53-4785-9686-dd460158e5d4
logging:
  level:
    org.springframework.web.servlet.DispatcherServlet: debug # sleuth链路追踪日志记录
management:
  endpoints:
    web:
      exposure:
        include: '*'
