server:
  port: 8000
spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8847
      config:
        server-addr: localhost:8847
        file-extension: yaml #指定yaml格式的配置
    gateway:
      discovery:
        locator:
          enabled: true # 开启注册中心路由模式
          lower-case-service-id: false # 使用小写微服务名称
      routes:
        - id: provider
          uri: lb://provider
          predicates:
            - Path=/provider/**
          filters:
            - StripPrefix=1
        - id: consumer
          uri: lb://consumer
          predicates:
            - Path=/consumer/**
          filters:
            - StripPrefix=1
        - id: auth
          uri: lb://auth
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
#        group: DEV_GROUP
#        namespace: 7d8f0f5a-6a53-4785-9686-dd460158e5d4
  sleuth:
    sampler:
      probability: 1 # 采样率0-1
  zipkin:
    base-url: http://localhost:9411

logging:
  level:
    org.springframework.web.servlet.DispatcherServlet: debug # sleuth链路追踪日志记录
management:
  endpoints:
    web:
      exposure:
        include: '*'
