server:
  port: 7000
spring:
  application:
    name: monitor
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8847
      config:
        server-addr: localhost:8847
        file-extension: yaml
  security: # 配置登录用户名和密码
    user:
      name: admin
      password: 123456
  boot:  # 不显示admin-server的监控信息
    admin:
      discovery:
        ignored-services: ${spring.application.name}

