server:
  port: 8800
spring:
  application:
    name: auth
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8847
      config:
        server-addr: localhost:8847
        file-extension: yaml
  sleuth:
    sampler:
      probability: 1 # 采样率0-1
  zipkin:
    base-url: http://localhost:9411
logging:
  level:
    org.springframework.web.servlet.DispatcherServlet: debug # sleuth链路追踪日志记录
management:
  endpoints:
    web:
      exposure:
        include: '*'
